# Generated by Django 4.1.4 on 2022-12-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_rename_ad_comment_ad_pk_ad_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
